/* Automatically generated by configure - do not modify! */
#define VERSION "1.1a"
#define PACKAGE "ushare"
#define PACKAGE_NAME "uShare"
#define SYSCONFDIR "/home/jji315/mount1/qca_branch/build/../apps/nas/media_server/ap152/etc"
#define LOCALEDIR "/home/jji315/mount1/qca_branch/build/../apps/nas/media_server/ap152/share/locale"
