# Automatically generated by configure - do not modify!
VERSION=1.1a
PREFIX=/home/jji315/mount1/qca_branch/build/../apps/nas/media_server/ap152
prefix=$(DESTDIR)$(PREFIX)
bindir=$(DESTDIR)${PREFIX}/bin
sysconfdir=$(DESTDIR)${PREFIX}/etc
localedir=$(DESTDIR)${PREFIX}/share/locale
MAKE=make
CC=mips-linux-uclibc-gcc
LN=ln
STRIP=mips-linux-uclibc-sstrip
INSTALLSTRIP=-s
EXTRALIBS= -lixml -lthreadutil -lpthread -L/home/jji315/mount1/qca_branch/build/../apps/nas/media_server/ap152/lib -lupnp -lrt -ldlna -lavdevice -lswscale -lavformat -lavcodec -lm -lavutil
OPTFLAGS= -I.. -W -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_GNU_SOURCE -O3 -DHAVE_LOCALE_H -DHAVE_SETLOCALE -DHAVE_LANGINFO_H -DHAVE_LANGINFO_CODESET -I/home/jji315/mount1/qca_branch/build/../apps/nas/media_server/ap152/lib -pthread -I/home/jji315/mount1/qca_branch/build/../apps/nas/media_server/ap152/include/upnp -DHAVE_DLNA
LDFLAGS= -L/home/jji315/mount1/qca_branch/build/../apps/nas/media_server/ap152/lib
INSTALL=/usr/bin/install -c
DEBUG=no
